name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make dev-env
      - name: lint
        run: make lint
      # disabled until a setup is available from github
      # - name: test
      #   env:
      #     V3IO_API: ${{ secrets.V3IO_API }}
      #     V3IO_ACCESS_KEY: ${{ secrets.V3IO_ACCESS_KEY }}
      #   run: make test
      - name: Set version
        run: make set-version
      - name: Build binary wheel and source tarball
        run: make dist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
